### ISSUE TITLE
flow_test_chamber example not working

### ISSUE THREAD

**Issue by jjderlatka** [cuspaceflight/octopus#11]
The `Orifice` object in example flow_test_chamber.py is initialized with nitrous - a `Fluid`, instead of a `Manifold`.

**Comment by astro-zilla** [comment]
erm doesn't seem to be for me, on the master branch? can someone verify that it's not just working for me due to a local file or something?

**Comment by jjderlatka** [comment]
Sorry my local filet were out of date.
