### ISSUE TITLE
Cp values from thermo not agreeing with polynomial

### ISSUE THREAD

**Issue by astro-zilla** [cuspaceflight/octopus#3]
https://github.com/cuspaceflight/white-giant-injector/blob/5615e23b7e62f883666052b4dd1fa25644fb918e/octopus/main.py#L152

The value of Cp from `Chemical.Cpl` appears to produce a result in the range of 900 J/kg.K, however the polynomial predicts in the range 2000 J/kg.K. I am inclined to believe the polynomial version as it produces a more believable value for omega, and have hence included it as a debug parameter, however this needs checking.

**Comment by HenryFree3** [comment]
I'm getting 2200 J/kg/K from thermo for 270 K, 30 bar. Dropping the pressure to 25 bar and it turns to vapour, Cp goes to ~850 - seems like it's just a phase problem?

There's also a method in the Fluid class to check phase that gets called when a manifold is created to do it automatically.

Tangential to this, my first thought for the orifice class was to define it using only its geometric properties and assign it to a manifold, so it inherits the upstream fluid conditions from there - what are your thoughts on that?

**Comment by astro-zilla** [comment]
I was using Cpl which is meant to give the liquid Cp at that pressure, as it's on the saturation line so could be difficult to make sure it's one of the other. I'll check it through again. 

In terms of using `Manifold` and `Fluid`, seems sensible, but with what would you parent the methods designed to compute fluid properties within the orifice? Would that be where an `Element` class comes in, defined by its `Orifice`, `Fluid` and `Manifold`? I'm very happy to refactor to something more user-friendly so let me know your thoughts.

**Comment by astro-zilla** [comment]
Or would you still use `Orifice` to parent the CFD methods?

**Comment by HenryFree3** [comment]
I think @dug20 had a similar issue in bamboo with inconsistent phase flow, which I think was solved just by overriding it.

Yeah I'm not entirely sure what the best way to do it is, it's all still open.
I was thinking of including all the mass flow calculation methods in `Orifice` as you said, and then defining element just with orifices, which might belong to different manifolds e.g. in the case of an unlike triplet

**Comment by astro-zilla** [comment]
Ok, that sounds like a good plan, I'll close this and try to make it work with potentially something a bit hacky. Another thing is that I'm actually using a lot of methods and attributes from the base thermo chemical class, could `octopus.Fluid` be modified to inherit it or have a `chemical` attribute that represents the thermo object?
